version: '3.3'
services:
  post_db:
    image: mongo:3.2
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - post_db:/data/db
    networks:
      docker_back_net:
        aliases:
          - comment_db
          - post_db

  ui:
#    build: ./ui
    image: ${USER_NAME}/ui:${UIVER}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      # - POST_SERVICE_HOST=post
      # - POST_SERVICE_PORT=5000
      # - COMMENT_SERVICE_HOST=comment
      # - COMMENT_SERVICE_PORT=9292
    ports:
      - ${PORTAPP}:9292/tcp
    networks:
      - docker_front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
#    build: ./post-py
    image: ${USER_NAME}/post:${POSTVER}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - docker_back_net
      - docker_front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
#    build: ./comment
    image: ${USER_NAME}/comment:${COMMENTVER}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - docker_back_net
      - docker_front_net

volumes:
  post_db:

networks:
  docker_back_net:
    external: true
  docker_front_net:
    external: true
